version: '3.8'
services:
  postgres_db:
    image: postgres:15.1-alpine
    container_name: imd-postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: "postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=100 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./docker-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
